name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: if you ever add an API folder later, add a build here and set skip_api_build accordingly

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          # Your site is at repository root (index.html, style.css)
          app_location: "/"
          output_location: "" # no build output folder
          skip_app_build: true  # do not try to run npm/yarn build
          # api_location: "api" # uncomment if you add an Azure Functions API later
        env:
          # Allow the workflow to continue even if token is missing (useful while wiring up)
          SKIP_DEPLOY_ON_MISSING_SECRETS: false
